name: htmd
channels:
  - anaconda
  - defaults
  - acellera
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - acemd-base=4.0.17=pyh4616a5c_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - ambertools=24.8=cuda_None_nompi_py310h834fefc_101
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h7c4b9e2_0
  - arpack=3.9.1=nompi_hf03ea27_102
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - biopython=1.85=py310h7c4b9e2_2
  - blas=2.136=openblas
  - blas-devel=3.9.0=36_h1ea3ea9_openblas
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py310hea6c23e_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.15.2=h3122c55_1
  - ca-certificates=2025.9.9=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=py310h06a4308_0
  - cffi=2.0.0=py310h34a4b09_0
  - cftime=1.6.4=py310h5eee18b_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h3788b33_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deeptime=0.4.5=py310h0158d43_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.17.0=py310h06a4308_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.0=py310h3406613_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gawk=5.3.1=hcd3d067_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.86.0=he175458_0
  - glib-tools=2.86.0=hf516916_0
  - glm=1.0.1=hdd259ec_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - greenlet=3.2.4=py310hea6c23e_1
  - griddataformats=1.0.2=pyhd8ed1ab_1
  - gsd=4.0.0=py310h7c4b9e2_1
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.12.1=nompi_py310hacc6608_103
  - harfbuzz=11.5.1=h15599e2_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.4=nompi_h2d575fe_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - htmd=2.5.6=py310h8e7c8fa_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jobqueues=1.0.8=pyh4616a5c_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lark=1.3.0=pyhd8ed1ab_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libboost=1.86.0=hed09d94_4
  - libboost-python=1.86.0=py310hc563356_4
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=36_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_3
  - libclang-cpp21.1=21.1.0=default_h99862b1_1
  - libclang13=21.1.0=default_h746c552_1
  - libcufft=11.4.1.4=h5888daf_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_5
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=36_h47877c9_openblas
  - liblapacke=3.9.0=36_h6ae95b6_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.2=nompi_h5ddbaa4_116
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - librdkit=2025.03.6=h3c5c181_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib=3.10.6=py310hff52083_1
  - matplotlib-base=3.10.6=py310hfde16b3_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - mdanalysis=2.9.0=py310h5eaa309_1
  - mdtraj=1.10.3=py310h4cdbd58_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2023.1.0=h213fc3f_46344
  - mmcif_pdbx=2.0.1=pyhd8ed1ab_1
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - moleculekit=1.10.4=py310h8e7c8fa_0
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mrcfile=1.5.4=pyhd8ed1ab_0
  - msgpack-python=1.1.1=py310h03d9f68_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf-fortran=4.6.1=nompi_ha5d1325_108
  - netcdf4=1.7.2=nompi_py310h5146f0f_101
  - networkx=3.4.2=pyh267e887_2
  - nglview=3.1.4=pyh620948e_0
  - nomkl=3.0=0
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.37=h29cc59b_0
  - nss=3.116=h445c969_0
  - numexpr=2.13.0=py310h34a7263_100
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - ocl-icd-system=1.0.0=1
  - openbabel=3.1.1=py310hbff9852_9
  - openblas=0.3.30=pthreads_h6ec200e_2
  - opencl-headers=2025.06.13=h5888daf_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openmm=8.3.1=py310h2992144_0
  - openpyxl=3.1.5=py310h05b0c27_2
  - openssl=3.5.3=h26f9b46_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py310h0158d43_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parmed=4.3.0=py310h78e4988_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pdb2pqr=3.6.1=pyhd8ed1ab_1
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310h6557065_3
  - pint=0.24.4=pyhe01879c_2
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - plumed=2.9.2=nompi_hda5c677_100
  - ply=3.11=pyhd8ed1ab_3
  - pmw=2.0.1=py310hff52083_1008
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propka=3.5.1=pyhecae5ae_2
  - protocolinterface=0.4.7=py_0
  - psfgen=2.0.0_3=0
  - psutil=7.1.0=py310h7c4b9e2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=h9a8bead_2
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycairo=1.28.0=py310h8c3e0f7_1
  - pycparser=2.22=pyh29332c3_1
  - pyedr=0.8.0=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymol-open-source=3.1.0=py310h0298fdb_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.11=py310hf392a12_1
  - pyqt5-sip=12.17.0=py310hf71b8c6_1
  - pyside6=6.9.2=py310hc4e1109_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.1=py310h431dcdc_4
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytng=0.3.3=py310habd4674_2
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.15=h3a7ef08_5
  - qt6-main=6.9.2=h5bd77bc_1
  - rdkit=2025.03.6=py310h8980e5f_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - reportlab=4.4.4=py310h7c4b9e2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=py310h06a4308_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rlpycairo=0.4.0=pyh6c17108_0
  - rpds-py=0.27.1=py310hd8f68c5_1
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - seaborn=0.13.2=py310h06a4308_3
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py310hf71b8c6_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlalchemy=2.0.43=py310h7c4b9e2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=hb60516a_3
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tidynamics=1.1.2=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py310h7c4b9e2_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310h7c4b9e2_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vina=1.1.101=0
  - wayland=1.24.0=h3e06ad9_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py310h139afa4_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - amberutils==21.0
      - edgembar==3.0
      - mmpbsa-py==16.0
      - packmol-memgen==2025.1.29
      - pdb4amber==22.0
      - pymsmt==22.0
      - pytraj==2.0.6
      - sander==22.0
prefix: /home/agarcia/GitHub/simulation_pipeline/pipeline/htmd
